language: node_js

services:
  - docker

before_install:
  - echo $(docker --version)
  - echo $(docker-compose --version)

install:
  - docker-compose up -d

script:
  - docker exec app /bin/bash -c  "npm run pre-commit"

after_failure:
  - docker-compose logs

cache:
  directories:
    - "node_modules"
