language: node_js

services:
  - docker

before_install:
  - docker --version
  - docker-compose --version

install:
    - docker-compose up -d

script:
  - docker exec $(docker ps -aqf "name=app") /bin/bash -c  "npm run pre-commit"

cache:
  directories:
    - "node_modules"
