language: node_js
dist: bionic

services:
  - docker

before_install:
  - docker --version
  - docker-compose --version

install:
  - docker-compose up -d --build

script:
  - docker exec app /bin/bash -c  "npm run pre-commit"

after_failure:
  - docker-compose logs

cache:
  directories:
    - "node_modules"
