language: node_js
services:
  - docker
before_install:
  - docker build . -f db.Dockerfile -t stub-rp-test-db
  - docker run -d -p15432:5432 stub-rp-test-db
  
script:
  - export DATABASE_CONNECTION_STRING=postgresql://postgres:@localhost:15432/stub_rp_test
  - npm run test
  - npm run acceptance-tests
cache:
  directories:
    - "node_modules"
